[[questions]]
id = "79942534-f414-41e6-944f-96d57905632c"
type = "MultipleChoice"
prompt.prompt = "What is the difference between using `+` and `push_str` to concatenate two strings?"
answer.answer = "`+` consumes ownership of the left-hand-side string, while `push_str` does not"
prompt.distractors = [
  "`push_str` is more efficient at runtime than `+`",
  "`push_str` consumes ownership of the right-hand-side string, while `+` does not",
  "There is no difference, they are aliases for the same function"
]
context = """
`push_str` takes `&mut self` while `+` takes `self`, so `+` consumes ownership and `push_str` does not.
"""

[[questions]]
id = "f1ab2171-96f0-4380-b16d-9055a9a00415"
type = "ShortAnswer"
prompt.prompt = """
What is the maximum number of times a heap allocation could occur in this program? Write your answer in digits, e.g. 0 or 1.

```
let s1 = String::from("tic");
let s2 = String::from("tac");
let s3 = String::from("toe");

let s = s1 + "-" + &s2 + "-" + &s3;
```
"""
answer.answer = "7"
context = """
One allocation for each call to `String::from`, and one allocation for every time `+` is called.
"""
